FROM rust:1.86-alpine3.20 AS builder
RUN apk add --no-cache musl-dev openssl-dev pkgconfig build-base perl perl-dev

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src

# Build the API binary
RUN cargo build --bin api

FROM debian:bullseye-slim AS final
COPY --from=builder /app/target/debug/api /app/main
WORKDIR /app
CMD ["./main"]
